version: '3'
services:
  socketio-chat-mongo:
    container_name: socketio-chat-mongo
    image: mongo:4.4.3
    volumes:
      - socketio-chat-mongo-data:/data/db
    command: '--bind_ip_all'
    ports:
      - 27017:27017
  socketio-chat-redis:
    container_name: socketio-chat-redis
    image: redis:latest
    volumes:
      - socketio-chat-redis-data:/data/redis
    ports:
      - 6379:6379
volumes:
  socketio-chat-mongo-data:
  socketio-chat-redis-data:
